### ISSUE TITLE
Raise KeyError(f"{not_found} not in index")

### ISSUE THREAD

**Issue by FaMoSi** [Svito-zar/gesticulator#11]
When running `bvh2features.py` with this **Dataset**:
```
gesture22.bvh
gesture20.bvh
/Users/Famosi/Desktop/Thesis/Datasets/Japanese/Motions/gesture22.bvh
/Users/Famosi/Desktop/Thesis/Datasets/Japanese/Motions/gesture20.bvh
```

I receive this **Error**:
```
KeyError: "['LeftShoulder_Yposition', 'RightForeArm_Yposition', 'LeftShoulder_Zposition', 'RightForeArm_Xposition', 'RightHand_Yposition', 'Head_Zposition', 'LeftForeArm_Zposition', 'RightShoulder_Xposition', 'LeftHand_Zposition', 'LeftShoulder_Xposition', 'Neck_Xposition', 'Spine_Xposition', 'LeftForeArm_Yposition', 'RightShoulder_Zposition', 'Spine_Zposition', 'LeftArm_Xposition', 'LeftArm_Zposition', 'Spine_Yposition', 'LeftArm_Yposition', 'LeftForeArm_Xposition', 'RightArm_Yposition', 'RightForeArm_Zposition', 'Neck_Zposition', 'Neck_Yposition', 'Spine1_Zposition', 'RightShoulder_Yposition', 'Head_Yposition', 'LeftHand_Xposition', 'RightArm_Zposition', 'RightHand_Zposition', 'RightHand_Xposition', 'LeftHand_Yposition', 'Head_Xposition', 'RightArm_Xposition', 'Spine1_Xposition', 'Spine1_Yposition'] not in index"
```

Here is the complete **Traceback**:
```
Traceback (most recent call last):
  File "bvh2features.py", line 87, in <module>
    extract_joint_angles(params.bvh_dir, files, params.dest_dir, params.pipeline_dir , fps=24)
  File "bvh2features.py", line 46, in extract_joint_angles
    out_data = data_pipe.fit_transform(data_all)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/pipeline.py", line 385, in fit_transform
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/pipeline.py", line 311, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/pipeline.py", line 728, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/base.py", line 571, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/Users/Famosi/Desktop/Thesis/Code/gesticulator/gesticulator/visualization/pymo/preprocessing.py", line 597, in transform
    t2.values = track.values[self.selected_channels]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/indexing.py", line 1552, in _get_listlike_indexer
    self._validate_read_indexer(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/indexing.py", line 1646, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['LeftShoulder_Yposition', 'RightForeArm_Yposition', 'LeftShoulder_Zposition', 'RightForeArm_Xposition', 'RightHand_Yposition', 'Head_Zposition', 'LeftForeArm_Zposition', 'RightShoulder_Xposition', 'LeftHand_Zposition', 'LeftShoulder_Xposition', 'Neck_Xposition', 'Spine_Xposition', 'LeftForeArm_Yposition', 'RightShoulder_Zposition', 'Spine_Zposition', 'LeftArm_Xposition', 'LeftArm_Zposition', 'Spine_Yposition', 'LeftArm_Yposition', 'LeftForeArm_Xposition', 'RightArm_Yposition', 'RightForeArm_Zposition', 'Neck_Zposition', 'Neck_Yposition', 'Spine1_Zposition', 'RightShoulder_Yposition', 'Head_Yposition', 'LeftHand_Xposition', 'RightArm_Zposition', 'RightHand_Zposition', 'RightHand_Xposition', 'LeftHand_Yposition', 'Head_Xposition', 'RightArm_Xposition', 'Spine1_Xposition', 'Spine1_Yposition'] not in index"
```

**Comment by Svito-zar** [comment]
Hi @FaMoSi .
This issue is created by line 40 in the script:
` ('jtsel', JointSelector(['Spine','Spine1','Spine2','Spine3','Neck','Neck1','Head','RightShoulder', 'RightArm', 'RightForeArm', 'RightHand', 'LeftShoulder', 'LeftArm', 'LeftForeArm', 'LeftHand'], include_root=True)),
      `
This was used to select certain joints only for our experiments.

You can remove this line from the script and it should run without an issue.

**Comment by FaMoSi** [comment]
Thanks @Svito-zar, this **resolved** my issue 👍 

#### Question:
I have the access to the [Trinity dataset](https://trinityspeechgesture.scss.tcd.ie) and I found that motion files are in .FBX extension. May I have to convert them from .FBX --> to .bhv? 

If **yes**:
1. Do you have any tips about how to do that?
2. Why in the [README.md](https://github.com/Svito-zar/gesticulator/blob/master/README.md) file this step is not specified?

Thanks for your time :)

**Comment by Svito-zar** [comment]
That's a good point, @FaMoSi . Yes, you need to convert FBX to BVH

1. You can do it using Blender, as I did: import motion from FBX and export it into BVH
2. I forgot about it :)
