### ISSUE TITLE
error with module pymo

### ISSUE THREAD

**Issue by ireneb612** [Svito-zar/gesticulator#42]
D:\PycharmProjects\gesticulator-master\venv\Scripts\python.exe D:/PycharmProjects/gesticulator-master/demo/demo.py
Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Using time-annotated JSON transcription 'input/jeremy_howard.json'
Traceback (most recent call last):
  File "D:\PycharmProjects\gesticulator-master\demo\demo.py", line 108, in <module>
    main(args)
  File "D:\PycharmProjects\gesticulator-master\demo\demo.py", line 28, in main
    visualize(motion.detach(), "temp.bvh", "temp.npy", "temp.mp4", 
  File "D:\PycharmProjects\gesticulator-master\demo\gesticulator\visualization\motion_visualizer\generate_videos.py", line 29, in visualize
    write_bvh((data_pipe_dir,), # write_bvh expects a tuple
  File "D:\PycharmProjects\gesticulator-master\demo\gesticulator\visualization\motion_visualizer\convert2bvh.py", line 11, in write_bvh
    data_pipeline = joblib.load(datapipe_file[0])
  File "D:\PycharmProjects\gesticulator-master\venv\lib\site-packages\joblib\numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "D:\PycharmProjects\gesticulator-master\venv\lib\site-packages\joblib\numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "C:\Users\UserPC.LAPTOP-F0JUUKDE\AppData\Local\Programs\Python\Python39\lib\pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "C:\Users\UserPC.LAPTOP-F0JUUKDE\AppData\Local\Programs\Python\Python39\lib\pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "C:\Users\UserPC.LAPTOP-F0JUUKDE\AppData\Local\Programs\Python\Python39\lib\pickle.py", line 1579, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'pymo.preprocessing'

This one above it is the error I get... I don't know how to deal since I don't know how to differently specify the directory to the module

**Comment by Svito-zar** [comment]
PyMo module should have been installed when you called the installation script, `python install_script.py` , it is defined in the `setup.py` of the `visualization` module: https://github.com/Svito-zar/gesticulator/blob/fe1c9b5a3eb2b07b64568411e5821bab2ad99ef6/gesticulator/visualization/setup.py 
Please ensure that PyMo was indeed installed. For example, by checking the list of installed packages.

Also, please note that `demo.py` should be called from the `demo` folder, but not from the root folder. I would recommend you to first enter `demo` folder and then call `demo.py` script. This could be independent from the issue above.

**Comment by ireneb612** [comment]
@Svito-zar  Yes I tried entering it but then all the path are wrong, that is the problem

**Comment by Svito-zar** [comment]
I think it is the easiest to just run it from the `demo` folder 
Did you solve your issue?

**Comment by Svito-zar** [comment]
closed due to inactivity
