### ISSUE TITLE
error when in demo.py

### ISSUE THREAD

**Issue by wujackjack** [Svito-zar/gesticulator#8]
Hi,
    when i run python demo.py in the `demo` folder, error occurs

> Traceback (most recent call last):
  File "demo.py", line 109, in <module>
    main(args)
  File "demo.py", line 31, in main
    data_pipe_dir = '../gesticulator/utils/data_pipe.sav')
  File "/data/wuzhongjun/gesticulator/gesticulator/visualization/motion_visualizer/generate_videos.py", line 32, in visualize
    20)
  File "/data/wuzhongjun/gesticulator/gesticulator/visualization/motion_visualizer/convert2bvh.py", line 13, in write_bvh
    inv_data = data_pipeline.inverse_transform(anim_clip)
AttributeError: 'numpy.ndarray' object has no attribute 'inverse_transform'

in the function `write_bvh` of file `convert2bvh.py`, the type of variable `data_pipeline` is `<class 'numpy.ndarray'>`，which has no attribute 'inverse_transform'.
I alter the file `data_pipe.sav` in `gesticulator/utils` to the one generated by script `bvh2features.py` in `gesticulator/data_processing`, and `data_pipeline` is

> Pipeline(memory=None,
     steps=[('dwnsampl', DownSampler(keep_all=False, tgt_fps=60)), ('root', RootTransformer(method='hip_centric', position_smoothing=0,
        rotation_smoothing=0)), ('mir', Mirror(append=True, axis='X')), ('jtsel', JointSelector(include_root=True,
       joints=['Spine', 'Spine1', 'Spine2', 'Spine3', ...ocapParameterizer(param_type='expmap')), ('cnst', ConstantsRemover(eps=1e-06)), ('np', Numpyfier())])

but still get error of 

> Traceback (most recent call last):
  File "demo.py", line 109, in <module>
    main(args)
  File "demo.py", line 31, in main
    data_pipe_dir = '../gesticulator/utils/data_pipe.sav')
  File "/data/wuzhongjun/gesticulator/gesticulator/visualization/motion_visualizer/generate_videos.py", line 32, in visualize
    20)
  File "/data/wuzhongjun/gesticulator/gesticulator/visualization/motion_visualizer/convert2bvh.py", line 13, in write_bvh
    inv_data = data_pipeline.inverse_transform(anim_clip)
  File "/home/wuzhongjun/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 458, in _inverse_transform
    Xt = transform.inverse_transform(Xt)
  File "/data/wuzhongjun/gesticulator/gesticulator/visualization/pymo/preprocessing.py", line 646, in inverse_transform
    new_mocap = self.org_mocap_.clone()
AttributeError: 'Numpyfier' object has no attribute 'org_mocap_'

Any idea to solve this problem? Hope to see your reply. Thanks a lot.

Zhongjun, Wu

**Comment by nagyrajmund** [comment]
Hi Wu,

Did you manage to resolve your problem?

**Comment by wujackjack** [comment]
hi, i regenerate the data_pipe.sav by bvh2features.py in gesticulator/data_processing and solve the problem
